{% set name = "raydp" %}
{% set version = "1.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/oap-project/raydp/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8f26bba9a090ff03741d1fef6d8640c82c1c13e87417be45fb338ca78c3fbb6b

build:
  number: 0
  skip: true  # [py<36 or py>=311]
  script_env:
    - GITHUB_CI=1
  script: './build.sh && pip install dist/raydp*.whl'

requirements:
  host:
    - python {{ python_min }}
    - pip
    - wheel
    - maven
    - grpcio-tools
    - openjdk ==8.*
    - pyspark >=3.2.4,<=3.5.4
  run:
    - python >={{ python_min }}
    - numpy
    - psutil
    - netifaces
    - pyarrow >=4.0.1
    - ray-all >=2.1.0
    - protobuf >3.19.5,<=3.20.3
    - pyspark >=3.2.4,<=3.5.4

test:
  imports:
    - raydp
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/oap-project/raydp
  summary: "RayDP: Distributed Data Processing on Ray"
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - yhori991
